# Deploy an artifact onto Prod
name: Promote jag-ccd  to Prod
on:
  workflow_dispatch:
    inputs:
      application:
        required: true
        description: What application you want to promote?
        type: choice
        options:
          - jag-ccd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout ArgoCD Repo
        id: gitops
        uses: actions/checkout@v4
        with:
          repository: bcgov-c/tenant-gitops-52e74e
          ref: main
          token: ${{ secrets.ARGO_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: gitops

      - name: Update API Helm Values and Commit
        id: helm-api
        if: ${{ github.event.inputs.application == 'jag-ccd' }}
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          cd gitops/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/ccdtag: .*/ccdtag: prod # Image Updated on $DATETIME/" ../deploy/prod_values.yaml
          sed -i "s/ccdVersion: .*/ccdVersion: v2.0.4 # Version Updated on $DATETIME/" ../deploy/prod_values.yaml
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git add .
          
          git add ../deploy/prod_values.yaml
          
          # Repackage Helm Chart      

          cd ccd-gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Prod jag-ccd image tag"
          git push origin main  # Update the branch name as needed
