name: ZAP Scanner for CCD APIs
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: feature/zapscanner
      
      - name: Update options prop file
        run: echo  "replacer.full_list(0).replacement=${{ secrets.BASIC_AUTH_HEADER_UNSECURE_DEV }}" >> /home/runner/work/jag-ccd/jag-ccd/options.prop

      - name: ZAP Scan - CCDUserMapping API
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: "soap"
          docker_name: "owasp/zap2docker-stable"
          issue_title: "ZAP Scan Report - CCDUserMapping API"
          target: "${{ secrets.JAG_CCD_UnSecureAPI_RouteUrl }}/ws/CCD.Source.CCDUserMapping.ws:ccdUserMapping?WSDL"   
          cmd_options: '-z "-config /zap/wrk/options.prop"'
