name: ZAP Scan - CCD WSDLS
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: feature/zapscanner

      - name: ZAP Automation
        uses: zaproxy/action-api-scan@v0.1.0
        run: ./zap.sh
